{{- $cmData := (include "env.cmData" (dict "dotenv" .Values.envFrom.dotenv "strip" .Values.envFrom.stripPrefixes) | fromYaml) -}}
{{- if gt (len $cmData) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "env.cmName" . }}
data:
{{- range $k, $v := $cmData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}