{{- if and .Values.envFrom.enabled .Values.envFrom.publicYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- $cmDefault := printf "%s-env" .Release.Name }}
  name: {{ .Values.envFrom.configMapName | default $cmDefault }}
data:
{{ .Values.envFrom.publicYaml | nindent 2 }}
{{- end }}