{{- if and .Values.envFrom.enabled .Values.envFrom.publicYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- $cmDefault := printf "%s-env" .Release.Name }}
  name: {{ .Values.envFrom.configMapName | default $cmDefault }}
  annotations:
    env-checksum: {{ .Values.podAnnotations.checksum | quote }}
    {{- if .Values.scriptJob.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
data:
{{ .Values.envFrom.publicYaml | nindent 2 }}
{{- end }}